### ISSUE TITLE
Can not get the Web Interface to work

### ISSUE THREAD

**Issue by APT256** [mmcc-xx/WhosAtMyFeeder#36]
So I am trying to set this up in an Unraid environment. I built Frigate with your config as an example, and it is running with no issues and the video feed looks good. I then installed WhosAtMyFeeder and gave this this simple config:

frigate:
  frigate_url: http://frigate:1984
  mqtt_server: mqtt
  mqtt_auth: false
  mqtt_username: 
  mqtt_password: 
  main_topic: frigate
  camera:
    - birdcam
  object: bird
classification:
  model: model.tflite
  threshold: 0.7
webui:
  port: 7766
  host: 192.168.100.69

When I try to go to the Web UI, I get: "Unable to connect. Firefox can’t establish a connection to the server at 192.168.100.69:7766." Looking at the docker logs, I am seeing these errors:
text  error  warn  system  array  login  

    client.connect(config['frigate']['mqtt_server'])
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "./speciesid.py", line 239, in run_mqtt_client
    client.connect(config['frigate']['mqtt_server'])
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
Cannot assign requested address
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Cannot assign requested address
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Cannot assign requested address
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Cannot assign requested address
Calling Main
Time: 2023-09-19 10:57:26.696
Python version
3.8.17 (default, Jun 13 2023, 16:09:51) 
[GCC 10.2.1 20210110]
Version info.
sys.version_info(major=3, minor=8, micro=17, releaselevel='final', serial=0)
Starting threads for Flask and MQTT
Starting flask app
Starting MQTT client. Connecting to: 192.168.100.69:1883
 * Serving Flask app 'webui'
 * Debug mode: off
Calling Main
Time: 2023-09-20 08:09:48.465
Python version
3.8.17 (default, Jun 13 2023, 16:09:51) 
[GCC 10.2.1 20210110]
Version info.
sys.version_info(major=3, minor=8, micro=17, releaselevel='final', serial=0)
Starting threads for Flask and MQTT
Starting flask app
 * Serving Flask app 'webui'
 * Debug mode: off
Starting MQTT client. Connecting to: 192.168.100.69
MQTT Connected
Calling Main
Time: 2023-09-20 09:44:41.823
Python version
3.8.17 (default, Jun 13 2023, 16:09:51) 
[GCC 10.2.1 20210110]
Version info.
sys.version_info(major=3, minor=8, micro=17, releaselevel='final', serial=0)
Starting threads for Flask and MQTT
Starting flask app
 * Serving Flask app 'webui'
 * Debug mode: off
Starting MQTT client. Connecting to: 192.168.100.69
MQTT Connected
Calling Main
Time: 2023-09-20 09:59:52.838
Python version
3.8.17 (default, Jun 13 2023, 16:09:51) 
[GCC 10.2.1 20210110]
Version info.
sys.version_info(major=3, minor=8, micro=17, releaselevel='final', serial=0)
Starting threads for Flask and MQTT
Starting flask app
 * Serving Flask app 'webui'
 * Debug mode: off
Starting MQTT client. Connecting to: mqtt
MQTT Connected

Any ideas what is wrong?

**Comment by APT256** [comment]
NM, I figured it out. It was a config error.
