### ISSUE TITLE
Exception while receiving image

### ISSUE THREAD

**Issue by JirikP** [mmcc-xx/WhosAtMyFeeder#38]
Hi, i got everything working with mosquitto broker and frigate but when frigate saves a picture and sends it over mqtt i get this log in WhosAtMyFeeder addon log.

Using HAOS on Odroid-M1
m.2 coral TPU
addon Frigate
addon WhosAtMyFeeder

```
Python version
3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Version info.
sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Starting threads for Flask and MQTT
Starting flask app
Starting MQTT client. Connecting to: 10.0.0.199
MQTT Connected
 * Serving Flask app 'webui'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:7767
 * Running on http://172.30.33.6:7767
Press CTRL+C to quit
172.30.32.2 - - [30/Oct/2023 21:05:26] "GET / HTTP/1.1" 200 -
skipping first message
Getting image for event: 1698696391.020262-n1t2to
Here's the URL: http://10.0.0.199:5000/api/events/1698696391.020262-n1t2to/snapshot.jpg
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 200, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 388, in request
    self.endheaders()
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 236, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 215, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffff9fefbac0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.0.0.199', port=5000): Max retries exceeded with url: /api/events/1698696391.020262-n1t2to/snapshot.jpg?crop=1&quality=95 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9fefbac0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/app/speciesid.py", line 282, in run_mqtt_client
    client.loop_forever()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/app/speciesid.py", line 106, in on_message
    response = requests.get(snapshot_url, params=params)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.0.0.199', port=5000): Max retries exceeded with url: /api/events/1698696391.020262-n1t2to/snapshot.jpg?crop=1&quality=95 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9fefbac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
172.30.32.2 - - [30/Oct/2023 21:07:40] "GET / HTTP/1.1" 200 -
```

And i have this error in Home Assistant Core

This error originated from a custom integration.

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:227
Integration: Frigate (documentation, issues)
First occurred: 8:29:07 PM (14 occurrences)
Last logged: 9:02:45 PM

```
Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Connect call failed ('172.30.33.3', 5000)]
Error fetching information from http://ccab4aaf-frigate:5000/api/stats: 502, message='Bad Gateway', url=URL('http://ccab4aaf-frigate:5000/api/stats')
Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Server disconnected
```

**Comment by JirikP** [comment]
Ok, now i changed the url from IP adrress to http://generatedletters-frigate:5000 and it seems to work. Any idea?
